# Kubik Configuration - Font Fixed 
font_path = fonts/Arimo-Regular.ttf 
font_path_bold = fonts/Arimo-Bold.ttf 
font_path_italic = fonts/Arimo-Italic.ttf 
font_path_bold_italic = fonts/Arimo-BoldItalic.ttf 
mono_font_path = fonts/Cousine-Regular.ttf 
mono_font_path_bold = fonts/Cousine-Bold.ttf 
mono_font_path_italic = fonts/Cousine-Italic.ttf 
mono_font_path_bold_italic = fonts/Cousine-BoldItalic.ttf 
fallback_font_path = fonts/DroidSansFallbackFull.ttf 
run_in_place = true 
